spring:
  datasource:
    url: jdbc:hsqldb:file:database/main/db
    username: hactchubas
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
